<?php

$wpdb->query("INSERT INTO `{$wpdb->prefix}improveseo_uk_states` (`id`, `name`, `country`, `country_short`) VALUES
	(1, 'Aberdeen City', 'Scotland', 'SCT'),
	(2, 'Aberdeenshire', 'Scotland', 'SCT'),
	(3, 'Moray', 'Scotland', 'SCT'),
	(4, 'Hertfordshire', 'England', 'ENG'),
	(5, 'Birmingham', 'England', 'ENG'),
	(6, 'Solihull', 'England', 'ENG'),
	(7, 'Sandwell', 'England', 'ENG'),
	(8, 'Warwickshire', 'England', 'ENG'),
	(9, 'Worcestershire', 'England', 'ENG'),
	(10, 'Dudley', 'England', 'ENG'),
	(11, 'Staffordshire', 'England', 'ENG'),
	(12, 'Bath and North East Somerset', 'England', 'ENG'),
	(13, 'Somerset', 'England', 'ENG'),
	(14, 'Wiltshire', 'England', 'ENG'),
	(15, 'Blackburn with Darwen', 'England', 'ENG'),
	(16, 'Lancashire', 'England', 'ENG'),
	(17, 'Bradford', 'England', 'ENG'),
	(18, 'Kirklees', 'England', 'ENG'),
	(19, 'North Yorkshire', 'England', 'ENG'),
	(20, 'Bournemouth', 'England', 'ENG'),
	(21, 'Poole', 'England', 'ENG'),
	(22, 'Dorset', 'England', 'ENG'),
	(23, 'Hampshire', 'England', 'ENG'),
	(24, 'Bury', 'England', 'ENG'),
	(25, 'Bolton', 'England', 'ENG'),
	(26, 'Brighton and Hove', 'England', 'ENG'),
	(27, 'East Sussex', 'England', 'ENG'),
	(28, 'West Sussex', 'England', 'ENG'),
	(29, 'Greater London', 'England', 'ENG'),
	(30, 'Kent', 'England', 'ENG'),
	(31, 'City of Bristol', 'England', 'ENG'),
	(32, 'South Gloucestershire', 'England', 'ENG'),
	(33, 'North Somerset', 'England', 'ENG'),
	(34, 'Belfast', 'Northern Ireland', 'NIR'),
	(35, 'Castlereagh', 'Northern Ireland', 'NIR'),
	(36, 'Lisburn', 'Northern Ireland', 'NIR'),
	(37, 'North Down', 'Northern Ireland', 'NIR'),
	(38, 'Ards', 'Northern Ireland', 'NIR'),
	(39, 'Down', 'Northern Ireland', 'NIR'),
	(40, 'Banbridge', 'Northern Ireland', 'NIR'),
	(41, 'Antrim', 'Northern Ireland', 'NIR'),
	(42, 'Newry and Mourne', 'Northern Ireland', 'NIR'),
	(43, 'Newtownabbey', 'Northern Ireland', 'NIR'),
	(44, 'Carrickfergus', 'Northern Ireland', 'NIR'),
	(45, 'Larne', 'Northern Ireland', 'NIR'),
	(46, 'Ballymena', 'Northern Ireland', 'NIR'),
	(47, 'Magherafelt', 'Northern Ireland', 'NIR'),
	(48, 'Derry', 'Northern Ireland', 'NIR'),
	(49, 'Limavady', 'Northern Ireland', 'NIR'),
	(50, 'Coleraine', 'Northern Ireland', 'NIR'),
	(51, 'Ballymoney', 'Northern Ireland', 'NIR'),
	(52, 'Moyle', 'Northern Ireland', 'NIR'),
	(53, 'County Armagh', 'Northern Ireland', 'NIR'),
	(54, 'Craigavon', 'Northern Ireland', 'NIR'),
	(55, 'Dungannon', 'Northern Ireland', 'NIR'),
	(56, 'County Fermanagh', 'Northern Ireland', 'NIR'),
	(57, 'Omagh', 'Northern Ireland', 'NIR'),
	(58, 'Cookstown', 'Northern Ireland', 'NIR'),
	(59, 'Strabane', 'Northern Ireland', 'NIR'),
	(60, 'Cumbria', 'England', 'ENG'),
	(61, 'Cambridgeshire', 'England', 'ENG'),
	(62, 'Essex', 'England', 'ENG'),
	(63, 'Suffolk', 'England', 'ENG'),
	(64, 'Cardiff', 'Wales', 'WLS'),
	(65, 'Bridgend', 'Wales', 'WLS'),
	(66, 'Rhondda Cynon Taff', 'Wales', 'WLS'),
	(67, 'Merthyr Tydfil', 'Wales', 'WLS'),
	(68, 'The Vale of Glamorgan', 'Wales', 'WLS'),
	(69, 'Caerphilly', 'Wales', 'WLS'),
	(70, 'Cheshire West and Chester', 'England', 'ENG'),
	(71, 'Flintshire', 'England', 'ENG'),
	(72, 'Wirral', 'England', 'ENG'),
	(73, 'Surrey', 'England', 'ENG'),
	(74, 'Coventry', 'England', 'ENG'),
	(75, 'Leicestershire', 'England', 'ENG'),
	(76, 'Cheshire East', 'England', 'ENG'),
	(77, 'Dundee City', 'Scotland', 'SCT'),
	(78, 'Angus', 'Scotland', 'SCT'),
	(79, 'Fife', 'Scotland', 'SCT'),
	(80, 'Derby', 'England', 'ENG'),
	(81, 'Derbyshire', 'England', 'ENG'),
	(82, 'Dumfries and Galloway', 'Scotland', 'SCT'),
	(83, 'County Durham', 'England', 'ENG'),
	(84, 'Sunderland', 'England', 'ENG'),
	(85, 'Darlington', 'England', 'ENG'),
	(86, 'Doncaster', 'England', 'ENG'),
	(87, 'Nottinghamshire', 'England', 'ENG'),
	(88, 'East Riding of Yorkshire', 'England', 'ENG'),
	(89, 'North Lincolnshire', 'England', 'ENG'),
	(90, 'Lincolnshire', 'England', 'ENG'),
	(91, 'North East Lincolnshire', 'England', 'ENG'),
	(92, 'Shropshire', 'England', 'ENG'),
	(93, 'City of London', 'England', 'ENG'),
	(94, 'City of Edinburgh', 'Scotland', 'SCT'),
	(95, 'Midlothian', 'Scotland', 'SCT'),
	(96, 'East Lothian', 'Scotland', 'SCT'),
	(97, 'West Lothian', 'Scotland', 'SCT'),
	(98, 'The Scottish Borders', 'Scotland', 'SCT'),
	(99, 'Falkirk', 'Scotland', 'SCT'),
	(100, 'Devon', 'England', 'ENG'),
	(101, 'Cornwall', 'England', 'ENG'),
	(102, 'Clackmannanshire', 'Scotland', 'SCT'),
	(103, 'Stirling', 'Scotland', 'SCT'),
	(104, 'Blackpool', 'England', 'ENG'),
	(105, 'Glasgow City', 'Scotland', 'SCT'),
	(106, 'East Renfrewshire', 'Scotland', 'SCT'),
	(107, 'West Dunbartonshire', 'Scotland', 'SCT'),
	(108, 'East Dunbartonshire', 'Scotland', 'SCT'),
	(109, 'North Lanarkshire', 'Scotland', 'SCT'),
	(110, 'South Lanarkshire', 'Scotland', 'SCT'),
	(111, 'Argyll and Bute', 'Scotland', 'SCT'),
	(112, 'Gloucestershire', 'England', 'ENG'),
	(113, 'Bracknell Forest', 'England', 'ENG'),
	(114, 'Guernsey', 'Guernsey', 'GG'),
	(115, 'Calderdale', 'England', 'ENG'),
	(116, 'Buckinghamshire', 'England', 'ENG'),
	(117, 'County of Herefordshire', 'England', 'ENG'),
	(118, 'Eilean Siar', 'Scotland', 'SCT'),
	(119, 'City of Kingston-upon-Hull', 'England', 'ENG'),
	(120, 'IOM', 'Isle of Man', 'IM'),
	(121, 'Norfolk', 'England', 'ENG'),
	(122, 'Highland', 'Scotland', 'SCT'),
	(123, 'Jersey', 'Jersey', 'JE'),
	(124, 'East Ayrshire', 'Scotland', 'SCT'),
	(125, 'South Ayrshire', 'Scotland', 'SCT'),
	(126, 'North Ayrshire', 'Scotland', 'SCT'),
	(127, 'Orkney Islands', 'Scotland', 'SCT'),
	(128, 'Perth and Kinross', 'Scotland', 'SCT'),
	(129, 'Liverpool', 'England', 'ENG'),
	(130, 'Sefton', 'England', 'ENG'),
	(131, 'Knowsley', 'England', 'ENG'),
	(132, 'St Helens', 'England', 'ENG'),
	(133, 'Powys', 'Wales', 'WLS'),
	(134, 'Leicester', 'England', 'ENG'),
	(135, 'Rutland', 'England', 'ENG'),
	(136, 'Northamptonshire', 'England', 'ENG'),
	(137, 'Wrexham', 'Wales', 'WLS'),
	(138, 'Denbighshire', 'Wales', 'WLS'),
	(139, 'Conwy', 'Wales', 'WLS'),
	(140, 'Gwynedd', 'Wales', 'WLS'),
	(141, 'Isle of Anglesey', 'Wales', 'WLS'),
	(142, 'Leeds', 'England', 'ENG'),
	(143, 'Luton', 'England', 'ENG'),
	(144, 'Central Bedfordshire', 'England', 'ENG'),
	(145, 'Greater Manchester', 'England', 'ENG'),
	(146, 'Trafford', 'England', 'ENG'),
	(147, 'Rochdale', 'England', 'ENG'),
	(148, 'Salford', 'England', 'ENG'),
	(149, 'Wigan', 'England', 'ENG'),
	(150, 'Tameside', 'England', 'ENG'),
	(151, 'Oldham', 'England', 'ENG'),
	(152, 'Medway', 'England', 'ENG'),
	(153, 'Milton Keynes', 'England', 'ENG'),
	(154, 'Buckingham', 'England', 'ENG'),
	(155, 'Bedford Borough', 'England', 'ENG'),
	(156, 'Newcastle Upon Tyne', 'England', 'ENG'),
	(157, 'Gateshead', 'England', 'ENG'),
	(158, 'North Tyneside', 'England', 'ENG'),
	(159, 'Northumberland', 'England', 'ENG'),
	(160, 'South Tyneside', 'England', 'ENG'),
	(161, 'Nottingham', 'England', 'ENG'),
	(162, 'Newport', 'Wales', 'WLS'),
	(163, 'Blaenau Gwent', 'Wales', 'WLS'),
	(164, 'Monmouthshire', 'Wales', 'WLS'),
	(165, 'Torfaen', 'Wales', 'WLS'),
	(166, 'Oxfordshire', 'England', 'ENG'),
	(167, 'Renfrewshire', 'Scotland', 'SCT'),
	(168, 'Inverclyde', 'Scotland', 'SCT'),
	(169, 'Peterborough', 'England', 'ENG'),
	(170, 'Inverness-shire', 'Scotland', 'SCT'),
	(171, 'Plymouth', 'England', 'ENG'),
	(172, 'Portsmouth', 'England', 'ENG'),
	(173, 'Isle Of Wight', 'England', 'ENG'),
	(174, 'Reading', 'England', 'ENG'),
	(175, 'Wokingham', 'England', 'ENG'),
	(176, 'West Berkshire', 'England', 'ENG'),
	(177, 'Thurrock', 'England', 'ENG'),
	(178, 'Sheffield', 'England', 'ENG'),
	(179, 'Rotherham', 'England', 'ENG'),
	(180, 'Barnsley', 'England', 'ENG'),
	(181, 'Swansea', 'Wales', 'WLS'),
	(182, 'Neath Port Talbot', 'Wales', 'WLS'),
	(183, 'Carmarthenshire', 'Wales', 'WLS'),
	(184, 'Pembrokeshire', 'Wales', 'WLS'),
	(185, 'Ceredigion', 'Wales', 'WLS'),
	(186, 'Hertford', 'England', 'ENG'),
	(187, 'Stockport', 'England', 'ENG'),
	(188, 'Slough', 'England', 'ENG'),
	(189, 'Windsor and Maidenhead', 'England', 'ENG'),
	(190, 'Swindon', 'England', 'ENG'),
	(191, 'Southampton', 'England', 'ENG'),
	(192, 'Southend-on-Sea', 'England', 'ENG'),
	(193, 'Stoke-on-Trent', 'England', 'ENG'),
	(194, 'London', 'England', 'ENG'),
	(195, 'Northumberland', 'Scotland', 'SCT'),
	(196, 'Telford and Wrekin', 'England', 'ENG'),
	(197, 'Torbay', 'England', 'ENG'),
	(198, 'Isles Of Scilly', 'England', 'ENG'),
	(199, 'Middlesbrough', 'England', 'ENG'),
	(200, 'Redcar and Cleveland', 'England', 'ENG'),
	(201, 'Stockton-on-Tees', 'England', 'ENG'),
	(202, 'Hartlepool', 'England', 'ENG'),
	(203, 'Warrington', 'England', 'ENG'),
	(204, 'Halton', 'England', 'ENG'),
	(205, 'Wakefield', 'England', 'ENG'),
	(206, 'Worcester', 'England', 'ENG'),
	(207, 'Walsall', 'England', 'ENG'),
	(208, 'Wolverhampton', 'England', 'ENG'),
	(209, 'York', 'England', 'ENG'),
	(210, 'Shetland Islands', 'Scotland', 'SCT');");